apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  labels:
    app: APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME 
    spec:
      containers:
      - name: APP_NAME
        image: IMAGE_HERE
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: VOLUME_PATH
            name: VOLUME_NAME
      volumes:
        - name: VOLUME_NAME
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: PERSISTENT_DISK_NAME
            fsType: ext4
      envFrom:
      - secretRef:
          name: SECRETS_NAME

        # kubectl apply -f deployment.yaml