apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
spec:
  selector:
    app: APP_NAME 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000 # External
    targetPort: EXPOSED_PORT # Container
    nodePort: 31110 # Node (Machine running the container)

    # kubectl apply -f service.yaml